### ISSUE TITLE
Bundling Error With Datalib

### ISSUE THREAD

**Issue by josep2** [jfhbrook/wzrd.in#110]
I tried: 

```javascript

var dl = require('datalib');
```

And got the following error: 

Bundling error: 

---FLAGRANT SYSTEM ERROR---

--- error #0: ---

(logs uuid: a7f280a0-4905-11e5-8593-6fa8cc569adf )

Error: "browserify exited with code 1"

code: 1
stderr: Error: Cannot find module 'browserify-shim' from '/tmp/datalib115722-17110-lbhq9x/node_modules/datalib'
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:50:17
    at process (/home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:119:43)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:128:21
    at load (/home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:60:43)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:66:22
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:107:15)

dirPath: /tmp/datalib115722-17110-lbhq9x

------

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

    https://github.com/jfhbrook/browserify-cdn/issues

Include the ENTIRETY of the contents of this message, and the maintainer(s)
can try to help you out.

Have a nice day!

**Comment by jfhbrook** [comment]
On the face of it, this sounds like an issue with the package.
