### ISSUE TITLE
Cannot find module 'esformatter' from '/tmp/esformatter-jsx115730

### ISSUE THREAD

**Issue by kevinsimper** [jfhbrook/wzrd.in#111]
```
---FLAGRANT SYSTEM ERROR---

--- error #0: ---


(logs uuid: 16bd9b60-4eff-11e5-ab69-8f6ede0fd6cb )

Error: "browserify exited with code 1"

code: 1
stderr: Error: Cannot find module 'esformatter' from '/tmp/esformatter-jsx115730-13003-yc3j2q/node_modules/esformatter-jsx/lib'
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:50:17
    at process (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:119:43)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:128:21
    at load (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:43)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:66:22
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:107:15)

dirPath: /tmp/esformatter-jsx115730-13003-yc3j2q
```

I used this code
```
var esformatter = require( 'esformatter' );
var esformatterJSX = require( 'esformatter-jsx' );
esformatter.register(esformatterJSX);
var output = esformatter.format("var GroceryList = React.createClass({  handleClick: function(i) {    console.log('You clicked: ' + this.props.items[i]);  },  render: function() {    return (      <div>        {this.props.items.map(function(item, i) {          return (            <div onClick={this.handleClick.bind(this, i)} key={i}>{item}</div>          );        }, this)}      </div>    );  }});React.render(  <GroceryList items={['Apple', 'Banana', 'Cranberry']} />, mountNode);");

console.log(output)
```

**Comment by jfhbrook** [comment]
I'm going to close this because it's almost definitely a peerDeps issue that's being tracked elsewhere. #130
