### ISSUE TITLE
@motorcycle/dom fails to bundle

### ISSUE THREAD

**Issue by Risto-Stevcev** [jfhbrook/wzrd.in#122]
It works if I try to browserify the module by itself on my pc (I'm using npm3). Here's the output:

https://wzrd.in/debug-bundle/@motorcycle%2Fdom

```
---FLAGRANT SYSTEM ERROR---

(logs uuid: 0a022f30-f404-11e5-a27b-c9bb8d56db80 )

Error: "browserify exited with code 1"

code: 1
stderr: Error: Cannot find module 'most/lib/source/MulticastSource' from '/tmp/@motorcycle%2Fdom116227-23032-9i8wnx/node_modules/@motorcycle%2Fdom/node_modules/@most/hold/dist'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:50:17
    at process (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:119:43)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:128:21
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:60:43)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:66:22
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:107:15)

dirPath: /tmp/@motorcycle%2Fdom116227-23032-9i8wnx

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

    https://github.com/jfhbrook/browserify-cdn/issues

Include the ENTIRETY of the contents of this message, and the maintainer(s)
can try to help you out.

Have a nice day!
```

**Comment by Risto-Stevcev** [comment]
Nvm, sorry. This is an issue with the `@motorcycle/dom` package itself because `most` is a `peerDependency` rather than a `dependency`, and I accidently had `most` installed:

```bash
[user@arch motorcyclejs-seed]$ browserify -r @motorcycle/dom  -s dom -o dom.js
Error: Cannot find module 'most' from '/home/user/git/javascript/motorcyclejs-seed/node_modules/@motorcycle/dom/lib'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```
