### ISSUE TITLE
Unable to use package on Esnext.

### ISSUE THREAD

**Issue by prakhar1989** [jfhbrook/wzrd.in#130]
Hi!

Thanks for this fantastic service! I was trying out a package - [react-tag-input](https://www.npmjs.com/package/react-tag-input) and I got this weird issue in the console. The message directed me to post this here, so that's why I'm here.

<details>
```
--- error #0: ---
(logs uuid: 52e09ea0-4317-11e6-8c65-79f7842fe37c )

Error: "browserify exited with code 1"

code: 1
stderr: Error: Cannot find module 'react-tag-input' from '/tmp/react-tag-input11666-1238-1kr0jwk/node_modules/react-tag-input'
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)

dirPath: /tmp/react-tag-input11666-1238-1kr0jwk
------
```
</details>

You can see what I have on ESNextBin [here](https://esnextb.in/?gist=ad8b5ea44409d0591472ea744ff6478e) and see the package source [here](https://github.com/prakhar1989/react-tags#react-tags). As a package author, I'd love to give an example of the package usage on ESNextBin, so if you have any ideas on what I can do to make this work, I'll highly appreciate it. Thanks! 👍

**Comment by jfhbrook** [comment]
Interesting. I would have to play with this more, but a few ideas:

1) Is this related to known problems with peer dependency resolution? I feel like this limitation is really painful for react demos.
2) What API call is esnextbin making? Is there a good way to find that out?

**Comment by jfhbrook** [comment]
Doesn't matter, I have repro here:

https://wzrd.in/standalone/react-tag-input@latest

3) Could this be related to the fact that I've been putting off upgrading wzrd.in to node 4? D:

**Comment by jfhbrook** [comment]
package.json looks well-formed but I see a lot of 

> https://github.com/prakhar1989/react-tags/blob/master/dist-modules/reactTags.js#L5

in the main export. Those can cause problems with browserify.

**Comment by jfhbrook** [comment]
One thing you can try doing too, is to make a tmpdir, go into it, make a package.json, npm install react-tag-manager and then run `node -pe "require('react-tag-manager')"` and see what happens?

**Comment by prakhar1989** [comment]
Thanks a ton for looking into this so quickly! The above suggestion is the first thing I tried and it seems to work fine - 

```
λ node -pe "require('react-tag-input').WithContext"
{ [Function: DragDropContextContainer]
  DecoratedComponent:
   { [Function]
     displayName: 'ReactTags',
     propTypes:
      { tags: [Object],
        placeholder: [Object],
        labelField: [Object],
        suggestions: [Object],
        delimiters: [Object],
        autofocus: [Object],
        inline: [Object],
        handleDelete: [Function: bound checkType],
        handleAddition: [Function: bound checkType],
        handleDrag: [Object],
        allowDeleteFromEmptyInput: [Object],
        handleInputChange: [Object],
        minQueryLength: [Object],
        shouldRenderSuggestions: [Object],
        removeComponent: [Object],
        autocomplete: [Object],
        readOnly: [Object],
        classNames: [Object] },
     getDefaultProps: { [Function: getDefaultProps] isReactClassApproved: {} },
     defaultProps:
      { placeholder: 'Add new tag',
        tags: [],
        suggestions: [],
        delimiters: [Object],
        autofocus: true,
        inline: true,
        allowDeleteFromEmptyInput: true,
        minQueryLength: 2,
        autocomplete: false,
        readOnly: false } },
  displayName: 'DragDropContext(ReactTags)',
  childContextTypes: { dragDropManager: [Function: bound checkType] } }
```

Let me know if there's anything else provide to help you debug! Thanks =)

**Comment by jfhbrook** [comment]
It might be a while until I can get back to this, just a heads-up.

**Comment by prakhar1989** [comment]
Sure no problem. Really appreciate any time you can put into this! Thank
you :)
